linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      # These 3 will detect many cases, but they do sense
      # if it's performance oriented code
      - hugeParam
      - rangeExprCopy
      - rangeValCopy

  errcheck:
    # Report a := b.(MyStruct) when a, ok := ... should be.
    check-type-assertions: true # Default: false

    # Report skipped checks:num, _ := strconv.Atoi(numStr).
    check-blank: true # Default: false

    # Function to skip.
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  govet:
    disable:
      - fieldalignment # I'm ok to waste some bytes

  nakedret:
    # No naked returns, ever.
    max-func-lines: 1

  tagliatelle:
    case:
      rules:
        json: snake # why it's not a snake by default?!
        yaml: snake # why it's not a snake by default?!
        xml: camel
        bson: camel
        avro: snake
        mapstructure: upperSnake


linters:
  fast: false
  enable-all: true
  disable:
    - containedctx
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - errchkjson
    - execinquery
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godox
    - goheader
    - gomnd
    - gomodguard
    - goprintffuncname
    - grouper
    - importas
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - musttag
    - nestif
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - testpackage
    - typecheck
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
exclude:
  - 'vendor/*/'
  - 'generated/*/'

run:
  skip-dirs-use-default: true
  issues:
  exclude-files:
    - '.*_mock\.go$'
    - 'main.go'

  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly