// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/quiz.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CLIQuizService_GetQuestions_FullMethodName  = "/quiz.CLIQuizService/GetQuestions"
	CLIQuizService_SubmitAnswers_FullMethodName = "/quiz.CLIQuizService/SubmitAnswers"
)

// CLIQuizServiceClient is the client API for CLIQuizService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CLIQuizServiceClient interface {
	GetQuestions(ctx context.Context, in *NoRequestParam, opts ...grpc.CallOption) (*QuestionsResponsePayload, error)
	SubmitAnswers(ctx context.Context, in *AnswersRequestPayload, opts ...grpc.CallOption) (*ResultResponsePayload, error)
}

type cLIQuizServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCLIQuizServiceClient(cc grpc.ClientConnInterface) CLIQuizServiceClient {
	return &cLIQuizServiceClient{cc}
}

func (c *cLIQuizServiceClient) GetQuestions(ctx context.Context, in *NoRequestParam, opts ...grpc.CallOption) (*QuestionsResponsePayload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionsResponsePayload)
	err := c.cc.Invoke(ctx, CLIQuizService_GetQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIQuizServiceClient) SubmitAnswers(ctx context.Context, in *AnswersRequestPayload, opts ...grpc.CallOption) (*ResultResponsePayload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultResponsePayload)
	err := c.cc.Invoke(ctx, CLIQuizService_SubmitAnswers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CLIQuizServiceServer is the server API for CLIQuizService service.
// All implementations must embed UnimplementedCLIQuizServiceServer
// for forward compatibility.
type CLIQuizServiceServer interface {
	GetQuestions(context.Context, *NoRequestParam) (*QuestionsResponsePayload, error)
	SubmitAnswers(context.Context, *AnswersRequestPayload) (*ResultResponsePayload, error)
	mustEmbedUnimplementedCLIQuizServiceServer()
}

// UnimplementedCLIQuizServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCLIQuizServiceServer struct{}

func (UnimplementedCLIQuizServiceServer) GetQuestions(context.Context, *NoRequestParam) (*QuestionsResponsePayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestions not implemented")
}
func (UnimplementedCLIQuizServiceServer) SubmitAnswers(context.Context, *AnswersRequestPayload) (*ResultResponsePayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAnswers not implemented")
}
func (UnimplementedCLIQuizServiceServer) mustEmbedUnimplementedCLIQuizServiceServer() {}
func (UnimplementedCLIQuizServiceServer) testEmbeddedByValue()                        {}

// UnsafeCLIQuizServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CLIQuizServiceServer will
// result in compilation errors.
type UnsafeCLIQuizServiceServer interface {
	mustEmbedUnimplementedCLIQuizServiceServer()
}

func RegisterCLIQuizServiceServer(s grpc.ServiceRegistrar, srv CLIQuizServiceServer) {
	// If the following call pancis, it indicates UnimplementedCLIQuizServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CLIQuizService_ServiceDesc, srv)
}

func _CLIQuizService_GetQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoRequestParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIQuizServiceServer).GetQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLIQuizService_GetQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIQuizServiceServer).GetQuestions(ctx, req.(*NoRequestParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLIQuizService_SubmitAnswers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswersRequestPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIQuizServiceServer).SubmitAnswers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLIQuizService_SubmitAnswers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIQuizServiceServer).SubmitAnswers(ctx, req.(*AnswersRequestPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// CLIQuizService_ServiceDesc is the grpc.ServiceDesc for CLIQuizService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CLIQuizService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quiz.CLIQuizService",
	HandlerType: (*CLIQuizServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuestions",
			Handler:    _CLIQuizService_GetQuestions_Handler,
		},
		{
			MethodName: "SubmitAnswers",
			Handler:    _CLIQuizService_SubmitAnswers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/quiz.proto",
}
